name: CI

on:
  push:
    branches: [ dev_kubernetes, dev, features/authentication, features/unit-testing ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  ci:
    uses: Projet-technique-Altair/altair-ci/.github/workflows/lab-api-ci.yml@main
